services:
  voux:
    image: ghcr.io/quintixlabs/voux/voux:latest
    container_name: voux # remove this if u wanna run more than 1 container
    ports:
      - "8787:8787"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=change-this-password
      # - PUBLIC_BASE_URL=https://your-domain.com
    volumes:
      - ./data:/app/data
